#!/bin/bash
###############################################################################
# setup nginx TLS session ticket keys and rotation for perfect forward secrecy
# on Centmin Mod Nginx based servers (centminmod.com)
# https://en.wikipedia.org/wiki/Forward_secrecy
# https://blog.cloudflare.com/tls-session-resumption-full-speed-and-secure/
###############################################################################
export PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin"
set -o errexit

uninstall_keys() {
  if [ -f /usr/lib/systemd/system/nginx.service ]; then
    /usr/bin/systemctl disable nginx-create-session-ticket-keys.service >/dev/null 2>&1
    /usr/bin/systemctl disable nginx-rotate-session-ticket-keys.service >/dev/null 2>&1
    /usr/bin/systemctl disable nginx-rotate-session-ticket-keys.timer >/dev/null 2>&1
    /usr/bin/systemctl disable usr-local-nginx-conf-session_ticket_keys.mount >/dev/null 2>&1
    /usr/bin/systemctl stop nginx-create-session-ticket-keys.service >/dev/null 2>&1
    /usr/bin/systemctl stop nginx-rotate-session-ticket-keys.service >/dev/null 2>&1
    /usr/bin/systemctl daemon-reload >/dev/null 2>&1
    /usr/bin/rm -f /usr/local/bin/manage-session-keys
    /usr/bin/rm -f /usr/lib/systemd/system/usr-local-nginx-conf-session_ticket_keys.automount
    /usr/bin/rm -f /usr/lib/systemd/system/nginx-rotate-session-ticket-keys.timer
    /usr/bin/rm -f /usr/lib/systemd/system/nginx-create-session-ticket-keys.service
    /usr/bin/rm -f /usr/lib/systemd/system/nginx-rotate-session-ticket-keys.service
    /usr/bin/rm -f /usr/lib/systemd/system/usr-local-nginx-conf-session_ticket_keys.mount
    /usr/bin/sed -i '/ssl_session_ticket_key/d' /usr/local/nginx/conf/ssl_include.conf
    if [ -f /usr/local/nginx/conf/ssl-session-ticket-keys.conf ]; then
      /usr/bin/rm -f /usr/local/nginx/conf/ssl-session-ticket-keys.conf
    fi
    if [[ -f /usr/local/nginx/conf/ssl_include.conf && "$(grep 'ssl-session-ticket-keys.conf' /usr/local/nginx/conf/ssl_include.conf)" ]]; then
      /usr/bin/sed -i '/ssl-session-ticket-keys.conf/d' /usr/local/nginx/conf/ssl_include.conf
    fi
    /usr/bin/systemctl reload nginx >/dev/null 2>&1
    echo "nginx session ticket keys uninstalled"
  fi
}

setup_keys() {
  if [ -f /usr/lib/systemd/system/nginx.service ]; then
    # setup Centmin Mod nginx TLS session keys
    wget -q -O /usr/local/bin/manage-session-keys https://raw.githubusercontent.com/centminmod/centminmod-nginx-session-ticket-keys/master/manage-session-keys
    chmod +x /usr/local/bin/manage-session-keys
    wget -q -O /usr/lib/systemd/system/usr-local-nginx-conf-session_ticket_keys.automount https://raw.githubusercontent.com/centminmod/centminmod-nginx-session-ticket-keys/master/usr-local-nginx-conf-session_ticket_keys.automount
    wget -q -O /usr/lib/systemd/system/nginx-rotate-session-ticket-keys.timer https://raw.githubusercontent.com/centminmod/centminmod-nginx-session-ticket-keys/master/nginx-rotate-session-ticket-keys.timer
    wget -q -O /usr/lib/systemd/system/nginx-create-session-ticket-keys.service https://raw.githubusercontent.com/centminmod/centminmod-nginx-session-ticket-keys/master/nginx-create-session-ticket-keys.service
    wget -q -O /usr/lib/systemd/system/nginx-rotate-session-ticket-keys.service https://raw.githubusercontent.com/centminmod/centminmod-nginx-session-ticket-keys/master/nginx-rotate-session-ticket-keys.service
    wget -q -O /usr/lib/systemd/system/usr-local-nginx-conf-session_ticket_keys.mount https://raw.githubusercontent.com/centminmod/centminmod-nginx-session-ticket-keys/master/usr-local-nginx-conf-session_ticket_keys.mount
    /usr/bin/systemctl daemon-reload >/dev/null 2>&1
    /usr/bin/systemctl enable usr-local-nginx-conf-session_ticket_keys.mount >/dev/null 2>&1
    /usr/bin/systemctl start usr-local-nginx-conf-session_ticket_keys.mount >/dev/null 2>&1
    /usr/bin/systemctl start nginx-create-session-ticket-keys.service >/dev/null 2>&1
    # /usr/bin/systemctl start nginx-rotate-session-ticket-keys.service >/dev/null 2>&1
    /usr/bin/systemctl enable nginx-create-session-ticket-keys.service >/dev/null 2>&1
    /usr/bin/systemctl enable nginx-rotate-session-ticket-keys.service >/dev/null 2>&1
    /usr/bin/systemctl enable nginx-rotate-session-ticket-keys.timer >/dev/null 2>&1
    echo "nginx session ticket keys setup"
    if [[ -f /usr/local/nginx/conf/ssl_include.conf && ! "$(grep 'ssl-session-ticket-keys.conf' /usr/local/nginx/conf/ssl_include.conf)" ]]; then
      echo 'include /usr/local/nginx/conf/ssl-session-ticket-keys.conf;' >> /usr/local/nginx/conf/ssl_include.conf
    fi
  else
    echo "/usr/lib/systemd/system/nginx.service not detected"
    exit 1
  fi
}

create_keys() {
  /usr/bin/umask 077

  cd /usr/local/nginx/conf/session_ticket_keys
  if [ -f /usr/local/nginx/conf/ssl-session-ticket-keys.conf ]; then
    /usr/bin/rm -f /usr/local/nginx/conf/ssl-session-ticket-keys.conf
    /usr/bin/touch /usr/local/nginx/conf/ssl-session-ticket-keys.conf
  else
    touch /usr/local/nginx/conf/ssl-session-ticket-keys.conf
  fi

  for i in 1 2 3 4 5 6 7 8; do
    /usr/bin/openssl rand -out ${i}.key 80
    echo "ssl_session_ticket_key /usr/local/nginx/conf/session_ticket_keys/${i}.key;" >> /usr/local/nginx/conf/ssl-session-ticket-keys.conf
  done
  echo "nginx session ticket keys created at:"
  echo "/usr/local/nginx/conf/session_ticket_keys"
  echo
  echo "include file at:"
  echo "/usr/local/nginx/conf/ssl-session-ticket-keys.conf"
}

rotate_keys() {
  /usr/bin/umask 077

  /usr/bin/cd /usr/local/nginx/conf/session_ticket_keys

  for i in 1 2 3 4 5 6 7 8; do
    /usr/bin/cp -p "/usr/local/nginx/conf/session_ticket_keys/$((i + 1)).key" /usr/local/nginx/conf/session_ticket_keys/tmp.key >/dev/null 2>&1
    /usr/bin/mv -f /usr/local/nginx/conf/session_ticket_keys/tmp.key "/usr/local/nginx/conf/session_ticket_keys/$i.key" >/dev/null 2>&1
  done
  if [ -f /usr/local/nginx/conf/session_ticket_keys/9.key ]; then
    /usr/bin/rm -f /usr/local/nginx/conf/session_ticket_keys/9.key >/dev/null 2>&1
  fi
  /usr/local/sbin/nginx -s reload >/dev/null 2>&1
}

status_keys(){
    echo
    echo "/usr/bin/systemctl status nginx-create-session-ticket-keys.service"
    /usr/bin/systemctl status nginx-create-session-ticket-keys.service
    # echo
    # echo "/usr/bin/systemctl status nginx-rotate-session-ticket-keys.service"
    # /usr/bin/systemctl status nginx-rotate-session-ticket-keys.service
    # echo
    # echo "/usr/bin/systemctl status nginx-rotate-session-ticket-keys.timer"
    # /usr/bin/systemctl status nginx-rotate-session-ticket-keys.timer
    echo
    echo "/usr/bin/systemctl status usr-local-nginx-conf-session_ticket_keys.mount"
    /usr/bin/systemctl status usr-local-nginx-conf-session_ticket_keys.mount
}

check_resumption(){
  domain=$1
  echo | openssl s_client -connect $domain:443 -reconnect -no_ticket -servername $domain 2>&1 | egrep 'New|Reused|Protocol|Cipher|Session-ID:|Master-Key'
}

help() {
  echo
  echo "Usage:"
  echo
  echo "$0 setup"
  echo "$0 create"
  echo "$0 rotate"
  echo "$0 uninstall"
  echo "$0 status"
  echo "$0 check-domain yourdomain.com"
}

case "$1" in
  create )
    create_keys
    ;;
  rotate )
    rotate_keys
    ;;
  setup )
    setup_keys
    ;;
  uninstall )
    uninstall_keys
    ;;
  status )
    status_keys
    ;;
  check-domain )
    if [ -n "$2" ]; then
      check_resumption "$2"
    else
      echo "$0 check-domain yourdomain.com"
    fi
    ;;
  * )
    help
    ;;
esac